### ISSUE TITLE
進館號13565、33141會頁面錯亂

### ISSUE THREAD

**Issue by HASTboya** [BRMAS/hast21#3]
![圖片](https://user-images.githubusercontent.com/50314092/109906197-05af7900-7cdb-11eb-8d18-49bfc8a474e8.png)

**Comment by moogoo78** [comment]
已修改, 因為鑑定的物種是空的造成顯示的 bug
https://github.com/BRMAS/hast21/commit/031e8cb75e9f383a60085b148093c4497b790350
