### ISSUE TITLE
今天點選填入的Microlepia屬突然整個消失?

### ISSUE THREAD

**Issue by HASTboya** [BRMAS/hast21#4]
館號：33188, 33191...

**Comment by HASTboya** [comment]
@moogoo78 Microlepia的種出來了，但只到屬的還是沒有？那我昨天選了屬的都無效了嗎？

**Comment by moogoo78** [comment]
被刪掉, 要看一下這個屬下面的種還在不在, 補資料回去的話, 鑑訂的物種還會不會在
